package dblp

import (
	"encoding/xml"
	"strings"
)

// Article was generated 2024-03-22 15:55:50 by tir on k9 with zek 0.1.22.
type Article struct {
	XMLName  xml.Name `xml:"article"`
	Text     string   `xml:",chardata"`
	Mdate    string   `xml:"mdate,attr"`
	Key      string   `xml:"key,attr"`
	Publtype string   `xml:"publtype,attr"`
	Cdate    string   `xml:"cdate,attr"`
	Author   []struct {
		Text  string `xml:",chardata"` // Paul Kocher, Daniel Genki...
		Orcid string `xml:"orcid,attr"`
		Aux   string `xml:"aux,attr"`
	} `xml:"author"`
	Title struct {
		Text   string `xml:",chardata"` // Spectre Attacks: Exploiti...
		Bibtex string `xml:"bibtex,attr"`
		Sup    struct {
			Text string `xml:",innerxml"`
		} `xml:"sup"`
		Sub struct {
			Text string `xml:",innerxml"`
		} `xml:"sub"`
	} `xml:"title"`
	Journal string `xml:"journal"` // meltdownattack.com, meltd...
	Year    string `xml:"year"`    // 2018, 2018, 1994, 1993, 1...
	Ee      []struct {
		Text string `xml:",chardata"` // https://spectreattack.com...
		Type string `xml:"type,attr"`
	} `xml:"ee"`
	Volume string   `xml:"volume"` // TR-0263-08-94-165, TR-022...
	Month  string   `xml:"month"`  // August, March, December, ...
	URL    []string `xml:"url"`    // db/journals/gtelab/index....
	Note   []struct {
		Text  string `xml:",chardata"` // This report is also avail...
		Type  string `xml:"type,attr"`
		Label string `xml:"label,attr"`
	} `xml:"note"`
	Cdrom     string `xml:"cdrom"`     // SQL/X3H2-90-412.pdf, SQL/...
	Publisher string `xml:"publisher"` // IBM Germany Science Cente...
	Editor    []struct {
		Text  string `xml:",chardata"` // Thomas Wetter, Rolf Engel...
		Orcid string `xml:"orcid,attr"`
	} `xml:"editor"`
	Pages  string `xml:"pages"`  // 1-41, 1-55, 1-24, 1-19, 1...
	Number string `xml:"number"` // 4, 1, 5, 3, 5, 1, 1, 4, 1...
	Cite   []struct {
		Text  string `xml:",chardata"` // journals/nca/HuangCL14a, ...
		Label string `xml:"label,attr"`
	} `xml:"cite"`
	Crossref  string `xml:"crossref"`  // journals/tcci/2011-3, jou...
	Publnr    string `xml:"publnr"`    // TR13-101, TR07-068, TR16-...
	Booktitle string `xml:"booktitle"` // Logical Methods in Comput...
}

func (article *Article) DOI() string {
	for _, ee := range article.Ee {
		if strings.HasPrefix(ee.Text, "https://doi.org/") {
			return strings.Replace(ee.Text, "https://doi.org/", "", 1)
		}
	}
	return ""
}

type Phdthesis struct {
	XMLName  xml.Name `xml:"phdthesis"`
	Text     string   `xml:",chardata"`
	Mdate    string   `xml:"mdate,attr"`
	Key      string   `xml:"key,attr"`
	Publtype string   `xml:"publtype,attr"`
	Author   []struct {
		Text  string `xml:",chardata"` // Kristian Kersting, Pavlos...
		Orcid string `xml:"orcid,attr"`
	} `xml:"author"`
	Title struct {
		Text string   `xml:",chardata"` // An Inductive Logic Progra...
		I    []string `xml:"i"`         // in Vitro, Top-down, Botto...
		Sub  []string `xml:"sub"`       // 2, 1-x, x
		Sup  []string `xml:"sup"`       // +, 2, 2, 2, 18, 18, 3
	} `xml:"title"`
	Year      string   `xml:"year"`      // 2005, 2020, 2009, 1992, 1...
	Pages     []string `xml:"pages"`     // 1-228, 1-152, 3-231, I-VI...
	Publisher string   `xml:"publisher"` // IOS Press, IOS Press, Spr...
	Series    struct {
		Text string `xml:",chardata"` // Frontiers in Artificial I...
		Href string `xml:"href,attr"`
	} `xml:"series"`
	Volume string   `xml:"volume"` // 148, 45, 40, 210, 98/19, ...
	School []string `xml:"school"` // University of Freiburg, G...
	ISBN   []struct {
		Text string `xml:",chardata"` // 978-1-58603-674-4, 978-1-...
		Type string `xml:"type,attr"`
	} `xml:"isbn"`
	Ee []struct {
		Text string `xml:",chardata"` // http://www.booksonline.io...
		Type string `xml:"type,attr"`
	} `xml:"ee"`
	Note []struct {
		Text string `xml:",chardata"` // base-search.net (ftethz:o...
		Type string `xml:"type,attr"`
	} `xml:"note"`
	Number string `xml:"number"` // LBL-32883, DS-96-3, 11045...
	Month  string `xml:"month"`  // September, September, Apr...
}

type Data struct {
	XMLName  xml.Name `xml:"data"`
	Text     string   `xml:",chardata"`
	Mdate    string   `xml:"mdate,attr"`
	Key      string   `xml:"key,attr"`
	Publtype string   `xml:"publtype,attr"`
	Author   []struct {
		Text  string `xml:",chardata"` // Chun-Yi Liu 0002, Wonil C...
		Orcid string `xml:"orcid,attr"`
	} `xml:"author"`
	Title struct {
		Text string `xml:",chardata"` // MBFGraph: An SSD-Based An...
		Sup  string `xml:"sup"`       // 2
	} `xml:"title"`
	Year  string `xml:"year"`  // 2023, 2022, 2022, 2014, 2...
	Month string `xml:"month"` // June, November, October, ...
	Ee    []struct {
		Text string `xml:",chardata"` // https://doi.org/10.5281/z...
		Type string `xml:"type,attr"`
	} `xml:"ee"`
	Publisher string `xml:"publisher"` // Zenodo, IEEE DataPort, IE...
	Rel       struct {
		Text  string `xml:",chardata"` // data/10/JacobFTBT19j, dat...
		Type  string `xml:"type,attr"`
		URI   string `xml:"uri,attr"`
		Label string `xml:"label,attr"`
		Sort  string `xml:"sort,attr"`
	} `xml:"rel"`
	Crossref string `xml:"crossref"` // data/10/HoffmannR18, data...
	Number   struct {
		Text  string `xml:",chardata"` // 2, 1, 0
		Label string `xml:"label,attr"`
	} `xml:"number"`
}

type Incollection struct {
	XMLName  xml.Name `xml:"incollection"`
	Text     string   `xml:",chardata"`
	Mdate    string   `xml:"mdate,attr"`
	Key      string   `xml:"key,attr"`
	Publtype string   `xml:"publtype,attr"`
	Author   []struct {
		Text  string `xml:",chardata"` // Bir Bhanu, Marijke De Soe...
		Orcid string `xml:"orcid,attr"`
	} `xml:"author"`
	Title struct {
		Text string `xml:",chardata"` // Ear Shape for Biometric I...
		Sup  []struct {
			Text string `xml:",chardata"` // &reg;, &reg;, x, â, x, ...
			I    string `xml:"i"`         // k, perf, TR
		} `xml:"sup"`
		I   []string `xml:"i"` // O, MQ, k, O, L, m, L, Q, ...
		Sub []struct {
			Text string `xml:",chardata"` // p, 1, 1, 1, 1, â, 2, â...
			I    string `xml:"i"`         // Î¸
			Sup  string `xml:"sup"`       // n
		} `xml:"sub"`
	} `xml:"title"`
	Pages     string `xml:"pages"`     // 372-378, 47, 1305-1306, 8...
	Year      string `xml:"year"`      // 2011, 2011, 2011, 2011, 2...
	Booktitle string `xml:"booktitle"` // Encyclopedia of Cryptogra...
	Ee        []struct {
		Text string `xml:",chardata"` // https://doi.org/10.1007/9...
		Type string `xml:"type,attr"`
	} `xml:"ee"`
	Crossref string `xml:"crossref"` // reference/crypt/2011, ref...
	URL      string `xml:"url"`      // db/reference/crypt/crypt2...
	Cite     []struct {
		Text  string `xml:",chardata"` // books/aw/Smith2008, ..., ...
		Label string `xml:"label,attr"`
	} `xml:"cite"`
	Number    string `xml:"number"` // Theory, Theory, Theory, T...
	Publisher struct {
		Text string `xml:",chardata"` // Morgan Kaufmann, Morgan K...
		Href string `xml:"href,attr"`
	} `xml:"publisher"`
	Note    string `xml:"note"`    // reprint from: EDBT 1990: ...
	Cdrom   string `xml:"cdrom"`   // Gray/chapter2.pdf, Gray/c...
	Chapter string `xml:"chapter"` // 27, 21
}

type Mastersthesis struct {
	XMLName xml.Name `xml:"mastersthesis"`
	Text    string   `xml:",chardata"`
	Mdate   string   `xml:"mdate,attr"`
	Key     string   `xml:"key,attr"`
	Author  string   `xml:"author"` // Stephan Vollmer, Vanessa ...
	Title   string   `xml:"title"`  // Portierung des DBLP-Syste...
	Year    string   `xml:"year"`   // 2006, 2007, 1992, 1997, 2...
	School  string   `xml:"school"` // Diplomarbeit, Universit&a...
	Ee      []struct {
		Text string `xml:",chardata"` // http://dbis.uni-trier.de/...
		Type string `xml:"type,attr"`
	} `xml:"ee"`
	Note struct {
		Text string `xml:",chardata"` // Diplomarbeit, Universit&a...
		Type string `xml:"type,attr"`
	} `xml:"note"`
	Pages     string `xml:"pages"`     // 1-141, 1-99
	Publisher string `xml:"publisher"` // VDM Verlag Dr. M&uuml;lle...
	ISBN      string `xml:"isbn"`      // 978-3-8364-7206-7
}

type Www struct {
	XMLName  xml.Name `xml:"www"`
	Text     string   `xml:",chardata"`
	Mdate    string   `xml:"mdate,attr"`
	Key      string   `xml:"key,attr"`
	Publtype string   `xml:"publtype,attr"`
	Title    []string `xml:"title"` // W3C: Extensible Styleshee...
	Ee       string   `xml:"ee"`    // http://www.w3.org/Style/X...
	Year     string   `xml:"year"`  // 2001, 1999, 1997, 2001, 1...
	Author   []struct {
		Text   string `xml:",chardata"` // Roy T. Fielding, Henrik F...
		Bibtex string `xml:"bibtex,attr"`
	} `xml:"author"`
	Editor []string `xml:"editor"` // Mary F. Fernandez, Jonath...
	Note   []struct {
		Text  string `xml:",chardata"` // Capital University of Eco...
		Type  string `xml:"type,attr"`
		Label string `xml:"label,attr"`
	} `xml:"note"`
	URL []struct {
		Text string `xml:",chardata"` // https://orcid.org/0000-00...
		Type string `xml:"type,attr"`
	} `xml:"url"`
	Cite     []string `xml:"cite"`     // conf/birthday/2013vapnik,...
	Crossref string   `xml:"crossref"` // homepages/19/3699, homepa...
}

type Inproceedings struct {
	XMLName  xml.Name `xml:"inproceedings"`
	Text     string   `xml:",chardata"`
	Mdate    string   `xml:"mdate,attr"`
	Key      string   `xml:"key,attr"`
	Publtype string   `xml:"publtype,attr"`
	Author   []struct {
		Text  string `xml:",chardata"` // Arnon Rosenthal, E. F. Co...
		Orcid string `xml:"orcid,attr"`
		Aux   string `xml:"aux,attr"`
	} `xml:"author"`
	Title struct {
		Text   string `xml:",chardata"` // The Future of Classic Dat...
		Bibtex string `xml:"bibtex,attr"`
		Sup    []struct {
			Text string `xml:",chardata"` // Simple, Ï, â, X, 1, *,...
			Sup  struct {
				Text string `xml:",chardata"` // n, h, 6, TM, 1-(1/d), y=z...
				Sup  string `xml:"sup"`       // 3:
			} `xml:"sup"`
			I   []string `xml:"i"`   // m, prime, 2, k, l, n, c, ...
			Sub string   `xml:"sub"` // ~, n/1, 1, 2
		} `xml:"sup"`
		I []struct {
			Text string   `xml:",chardata"` // K, p, HOL, R, C, pi, pi, ...
			Sub  []string `xml:"sub"`       // DDQ, Î±, p, p, n, L, H, n...
			Sup  []string `xml:"sup"`       // 2, o, 2, IA, T, link, m, ...
			I    string   `xml:"i"`         // L
		} `xml:"i"`
		Sub []struct {
			Text string   `xml:",chardata"` // &times;, n, 0, 2, n, 1, 1...
			I    []string `xml:"i"`         // r, p, Ï, Î±, K, T, NRI, ...
			Sup  struct {
				Text string `xml:",chardata"` // m, m, -1, 6...137, 6...16...
				I    string `xml:"i"`         // m, n
			} `xml:"sup"`
			Sub string `xml:"sub"` // 2(x), 3,, 4, 2, 5), 2), n...
		} `xml:"sub"`
		Tt string `xml:"tt"` // dlv, Prop, k
	} `xml:"title"`
	Booktitle string   `xml:"booktitle"` // SWEE, IFIP Working Confer...
	Year      string   `xml:"year"`      // 1998, 1974, 1991, 1991, 1...
	URL       string   `xml:"url"`       // db/conf/swee/swee1998.htm...
	Crossref  []string `xml:"crossref"`  // conf/swee/1998, conf/ds/1...
	Ee        []struct {
		Text string `xml:",chardata"` // http://www.mitre.org/supp...
		Type string `xml:"type,attr"`
	} `xml:"ee"`
	Month string `xml:"month"` // January
	Pages string `xml:"pages"` // 179-200, 402-427, 632-644...
	Note  struct {
		Text string `xml:",chardata"` // IBM Research Report RJ 13...
		Type string `xml:"type,attr"`
	} `xml:"note"`
	Cdrom  []string `xml:"cdrom"`  // DS/DS1974/P179.pdf, CIKM1...
	Volume string   `xml:"volume"` // 335, 48, 335, 48, 335, 48...
	Number string   `xml:"number"` // 1, 1, 1, 1, 1, 2, 1, 1, 1...
	Cite   []struct {
		Text  string `xml:",chardata"` // journals/cacm/Allen83, jo...
		Label string `xml:"label,attr"`
	} `xml:"cite"`
	Editor []struct {
		Text  string `xml:",chardata"` // Andreas Abecker, Ludger v...
		Orcid string `xml:"orcid,attr"`
	} `xml:"editor"`
}

type Proceedings struct {
	XMLName  xml.Name `xml:"Proceedings"`
	Text     string   `xml:",chardata"`
	Mdate    string   `xml:"mdate,attr"`
	Key      string   `xml:"key,attr"`
	Publtype string   `xml:"publtype,attr"`
	Editor   []struct {
		Text  string `xml:",chardata"` // Dieter Baum, Norbert Th. ...
		Orcid string `xml:"orcid,attr"`
	} `xml:"editor"`
	Title struct {
		Text string   `xml:",chardata"` // MMB '99, Messung, Modelli...
		Sub  string   `xml:"sub"`       // E
		Sup  []string `xml:"sup"`       // e, st, th, th, th, th, 2,...
		I    string   `xml:"i"`         // i, i*, i, and
	} `xml:"title"`
	Booktitle string `xml:"booktitle"` // MMB (Kurzvortr&auml;ge), ...
	Series    []struct {
		Text string `xml:",chardata"` // Universit&auml;t Trier, M...
		Href string `xml:"href,attr"`
	} `xml:"series"`
	Volume    string `xml:"volume"` // 99-16, 8615, 11370, 8670,...
	Year      string `xml:"year"`   // 1999, 2015, 2013, 2014, 2...
	URL       string `xml:"url"`    // db/conf/mmb/mmb99k.html, ...
	Publisher []struct {
		Text string `xml:",chardata"` // Springer, Springer, Sprin...
		Href string `xml:"href,attr"`
	} `xml:"publisher"`
	ISBN []struct {
		Text string `xml:",chardata"` // 978-3-319-20882-4, 978-1-...
		Type string `xml:"type,attr"`
	} `xml:"isbn"`
	Ee []struct {
		Text string `xml:",chardata"` // https://doi.org/10.1007/9...
		Type string `xml:"type,attr"`
	} `xml:"ee"`
	Number string   `xml:"number"` // 6, 3, 2, 1, 2, 1, 6, 1, 5...
	Author []string `xml:"author"` // Russ B. Altman, A. Keith ...
	Note   []struct {
		Text string `xml:",chardata"` // 0-7695-1393-X, 0-7695-057...
		Type string `xml:"type,attr"`
	} `xml:"note"`
	Pages string `xml:"pages"` // 1-528, I-XV, 1-321, i-xii...
	Cite  []struct {
		Text  string `xml:",chardata"` // ..., ..., journals/cj/Atk...
		Label string `xml:"label,attr"`
	} `xml:"cite"`
	Journal string `xml:"journal"` // SIGMOD Record, SIGMOD Rec...
	School  string `xml:"school"`  // University of Bern
	Address string `xml:"address"` // New York, New York, New Y...
}

type Book struct {
	XMLName  xml.Name `xml:"book"`
	Text     string   `xml:",chardata"`
	Mdate    string   `xml:"mdate,attr"`
	Key      string   `xml:"key,attr"`
	Publtype string   `xml:"publtype,attr"`
	Editor   []struct {
		Text  string `xml:",chardata"` // Helen Bolke-Hermanns, Joo...
		Orcid string `xml:"orcid,attr"`
	} `xml:"editor"`
	Title struct {
		Text string   `xml:",chardata"` // 50 Jahre Studiengang Info...
		Sup  []string `xml:"sup"`       // nd, &reg;, &reg;, nd, nd,...
		I    []string `xml:"i"`         // CAD/CAM, NC
		Sub  string   `xml:"sub"`       // n, n, â
	} `xml:"title"`
	Publisher struct {
		Text string `xml:",chardata"` // RWTH Aachen, Fachgruppe I...
		Href string `xml:"href,attr"`
	} `xml:"publisher"`
	Year string `xml:"year"` // 2022, 2013, 1993, 2014, 2...
	Ee   []struct {
		Text string `xml:",chardata"` // https://www.informatik.rw...
		Type string `xml:"type,attr"`
	} `xml:"ee"`
	ISBN []struct {
		Text string `xml:",chardata"` // 978-1-4503-2309-3, 1-5739...
		Type string `xml:"type,attr"`
	} `xml:"isbn"`
	Author []struct {
		Text   string `xml:",chardata"` // Uwe M. Borghoff, John Lio...
		Orcid  string `xml:"orcid,attr"`
		Bibtex string `xml:"bibtex,attr"`
	} `xml:"author"`
	Pages   []string `xml:"pages"`   // 1-168, 1-250, 1-262, 1-22...
	Journal string   `xml:"journal"` // Forschungsberichte, TU Mu...
	School  []string `xml:"school"`  // TU Munich, Germany, Dortm...
	Volume  string   `xml:"volume"`  // TUM I 9326, 11, 2, 1, 3, ...
	Series  struct {
		Text string `xml:",chardata"` // Computer classics revisit...
		Href string `xml:"href,attr"`
	} `xml:"series"`
	URL       string `xml:"url"`       // db/reference/crypt/crypt2...
	Booktitle string `xml:"booktitle"` // Handbook of Ambient Assis...
	Note      struct {
		Text string `xml:",chardata"` // Living reference work, sn...
		Type string `xml:"type,attr"`
	} `xml:"note"`
	Crossref string `xml:"crossref"` // reference/docip/2014, ref...
	Cdrom    string `xml:"cdrom"`    // Wiederhold/toc.html
	Cite     []struct {
		Text  string `xml:",chardata"` // journals/cacm/AhoC75, boo...
		Label string `xml:"label,attr"`
	} `xml:"cite"`
	Month string `xml:"month"` // April
}
